/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as ApiAutumnRouteRouteImport } from './routes/api/autumn/route'
import { Route as ApiDuckdbQueryRouteImport } from './routes/api/duckdb/query'
import { Route as ApiAutumnSplatRouteImport } from './routes/api/autumn/$'
import { Route as AuthedTableTableRouteImport } from './routes/_authed/table.$table'

const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApiAutumnRouteRoute = ApiAutumnRouteRouteImport.update({
  id: '/api/autumn',
  path: '/api/autumn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDuckdbQueryRoute = ApiDuckdbQueryRouteImport.update({
  id: '/api/duckdb/query',
  path: '/api/duckdb/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutumnSplatRoute = ApiAutumnSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiAutumnRouteRoute,
} as any)
const AuthedTableTableRoute = AuthedTableTableRouteImport.update({
  id: '/table/$table',
  path: '/table/$table',
  getParentRoute: () => AuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/api/autumn': typeof ApiAutumnRouteRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/table/$table': typeof AuthedTableTableRoute
  '/api/autumn/$': typeof ApiAutumnSplatRoute
  '/api/duckdb/query': typeof ApiDuckdbQueryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/api/autumn': typeof ApiAutumnRouteRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/table/$table': typeof AuthedTableTableRoute
  '/api/autumn/$': typeof ApiAutumnSplatRoute
  '/api/duckdb/query': typeof ApiDuckdbQueryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/api/autumn': typeof ApiAutumnRouteRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/table/$table': typeof AuthedTableTableRoute
  '/api/autumn/$': typeof ApiAutumnSplatRoute
  '/api/duckdb/query': typeof ApiDuckdbQueryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/features'
    | '/api/autumn'
    | '/dashboard'
    | '/table/$table'
    | '/api/autumn/$'
    | '/api/duckdb/query'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/features'
    | '/api/autumn'
    | '/dashboard'
    | '/table/$table'
    | '/api/autumn/$'
    | '/api/duckdb/query'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/about'
    | '/features'
    | '/api/autumn'
    | '/_authed/dashboard'
    | '/_authed/table/$table'
    | '/api/autumn/$'
    | '/api/duckdb/query'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  FeaturesRoute: typeof FeaturesRoute
  ApiAutumnRouteRoute: typeof ApiAutumnRouteRouteWithChildren
  ApiDuckdbQueryRoute: typeof ApiDuckdbQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/autumn': {
      id: '/api/autumn'
      path: '/api/autumn'
      fullPath: '/api/autumn'
      preLoaderRoute: typeof ApiAutumnRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/duckdb/query': {
      id: '/api/duckdb/query'
      path: '/api/duckdb/query'
      fullPath: '/api/duckdb/query'
      preLoaderRoute: typeof ApiDuckdbQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autumn/$': {
      id: '/api/autumn/$'
      path: '/$'
      fullPath: '/api/autumn/$'
      preLoaderRoute: typeof ApiAutumnSplatRouteImport
      parentRoute: typeof ApiAutumnRouteRoute
    }
    '/_authed/table/$table': {
      id: '/_authed/table/$table'
      path: '/table/$table'
      fullPath: '/table/$table'
      preLoaderRoute: typeof AuthedTableTableRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedTableTableRoute: typeof AuthedTableTableRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedTableTableRoute: AuthedTableTableRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface ApiAutumnRouteRouteChildren {
  ApiAutumnSplatRoute: typeof ApiAutumnSplatRoute
}

const ApiAutumnRouteRouteChildren: ApiAutumnRouteRouteChildren = {
  ApiAutumnSplatRoute: ApiAutumnSplatRoute,
}

const ApiAutumnRouteRouteWithChildren = ApiAutumnRouteRoute._addFileChildren(
  ApiAutumnRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  FeaturesRoute: FeaturesRoute,
  ApiAutumnRouteRoute: ApiAutumnRouteRouteWithChildren,
  ApiDuckdbQueryRoute: ApiDuckdbQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
